/**
 * Central string table (German first, see CLAUDE.md conventions).
 * All player-facing text must come from here — no literals in UI/world code.
 * Card/enemy IDs are English snake_case; display names live here.
 */
export const strings = {
  game: {
    title: 'Crystal Cove',
    helloIsland: 'Hallo Insel',
  },
  ui: {
    overlayReady: 'UI-Overlay aktiv',
    startTestCombat: 'Testkampf starten',
  },
  combat: {
    endTurn: 'Zug beenden',
    playerName: 'Du',
    retreatAttempt: 'Rückzugsversuch',
    drawPile: 'Nachziehstapel',
    discardPile: 'Ablagestapel',
    energy: 'Energie',
    block: 'Block',
    hp: 'Lebenspunkte',
    turn: 'Runde',
    locationChip: 'Heimatbucht · Dichte {density}',
    locationChipCleansed: 'Heimatbucht · Gereinigt',
    victoryTitle: 'Sieg!',
    lootHeading: 'Beute',
    defeatTitle: 'Erschöpft …',
    defeatBody: 'Du wachst sicher in deinem Zelt auf — vollständig erholt.',
    /** Defeat loot penalty (docs/03: 50 % der Run-Beute an die Schatten). */
    defeatLossHeading: 'Beute verloren',
    defeatNoLoss: 'Keine Beute verloren.',
    retreatedTitle: 'Rückzug gelungen',
    retreatedBody: 'Du entkommst ohne Beute.',
    backToIsland: 'Zurück zur Insel',
    unplayable: 'Unspielbar',
    ignoresBlock: 'ignoriert Block',
    /** Extra text on emphasized boss telegraphs (docs/07 Erdstampfer) —
     * information never via size/color alone (docs/11). */
    intentEmphasis: 'Achtung: schwerer Schlag!',
    dungeonLocationChip: '{dungeon} · Raum {room}/{total}',
    intents: {
      attack: 'Angriff',
      defend: 'Verteidigung',
      buff: 'Verstärkung',
      debuff: 'Schwächung',
      deck: 'Deck-Störung',
    },
    cardTypes: {
      attack: 'Angriff',
      skill: 'Fertigkeit',
      power: 'Kraft',
      dish: 'Gericht',
      status: 'Zustand',
    },
  },
  statuses: {
    strength: { name: 'Stärke', description: '+1 Schaden pro Punkt bei Angriffen.' },
    vulnerable: { name: 'Verwundbar', description: 'Erleidet 50 % mehr Angriffsschaden.' },
    weak: { name: 'Schwäche', description: 'Verursacht 25 % weniger Angriffsschaden.' },
    poison: { name: 'Gift', description: 'Verliert am Zugende HP in Höhe der Stapel, dann −1.' },
    retaliate: {
      name: 'Vergeltung',
      description: 'Angreifer erleiden Schaden in Höhe der Stapel.',
    },
  },
  world: {
    harvestNodes: {
      tree: 'Baum',
      rock: 'Fels',
      copper_vein: 'Kupferader',
      berry_bush: 'Beerenstrauch',
    },
    harvestPrompt: '[E] {node} ernten',
    farmPlot: 'Beet',
    plantPrompt: 'Pflanzen: [1] Beeren · [2] Kürbis · [3] Chili',
    growingPrompt: '{crop} wächst — noch {left}x schlafen',
    ripePrompt: '[E] {crop} ernten',
    sleepPrompt: '[E] Schlafen',
    sleepDone: 'Gut geschlafen! Die Insel erholt sich.',
    cropNames: {
      berry: 'Beeren',
      pumpkin: 'Kürbis',
      chili: 'Chili',
    },
    harvestGain: '+{amount} {item}',
    lootToastHeading: 'Beute erhalten',
    npcTalkPrompt: '[E] Mit {npc} sprechen',
  },
  dialog: {
    /** Blinking ▼ carries this label — never a glyph alone (docs/11). */
    continueLabel: 'Weiter',
    continueHint: 'Weiter: Klick oder Leertaste',
    choicesLabel: 'Antwort wählen',
    portraitLabel: 'Porträt: {npc}',
  },
  /** Dialog box texts (docs/13: max 2 Zeilen à ~60 Zeichen pro Box;
   * Lumen-Regel docs/06: max 1 Satz pro Box). Keys ← data/dialogs.ts. */
  dialogLines: {
    lumen_intro_1: 'Da bist du ja endlich — ich bin Lumen!',
    lumen_intro_2: 'Die Insel hat dich schon erwartet.',
  },
  /** Choice labels (docs/13: V1 nur Quest-Annahme und Piya-Handel). */
  dialogChoices: {
    quest_accept: 'Annehmen',
    quest_later: 'Später',
    trade_open: 'Zeig mir deine Waren',
  },
  save: {
    recoveryNotice:
      'Spielstand wiederhergestellt: Der letzte Speicherstand war beschädigt, die Sicherungskopie wurde geladen.',
    recoveryDismiss: 'OK',
  },
  inventory: {
    title: 'Inventar',
    toggleHint: '[I] Inventar',
    empty: 'Noch nichts gesammelt.',
  },
  items: {
    wood: 'Holz',
    stone: 'Stein',
    shadow_fiber: 'Schattenfaser',
    shadow_dust: 'Schattenstaub',
    berry: 'Beere',
    tough_leather: 'Zähes Leder',
    meat: 'Fleisch',
    vine: 'Ranke',
    resin: 'Harz',
    copper_ore: 'Kupfererz',
    beetle_shell: 'Käferpanzer',
    feather: 'Feder',
    shiny_trinket: 'Glitzerkram',
    heart_thorn: 'Herzdorn',
    thorn_ring: 'Dornenring',
    pumpkin: 'Kürbis',
    chili: 'Chili',
    fish: 'Fisch',
    honey: 'Honig',
  },
  stations: {
    smithy: 'Schmiede',
    kitchen: 'Küche',
    deck_chest: 'Deck-Truhe',
  },
  deckChest: {
    collectionHeading: 'Sammlung',
    deckHeading: 'Deck ({count}/{size})',
    addToDeck: 'Ins Deck',
    removeFromDeck: 'Entfernen',
    disenchant: 'Zerlegen',
    disenchantConfirm: 'Wirklich zerlegen?',
    disenchantYes: 'Ja, zerlegen',
    disenchantNo: 'Abbrechen',
    refundPreview: 'Erstattung: {refund}',
    refundNothing: 'Erstattung: nichts',
    notDisenchantable: 'Starterkarte — nicht zerlegbar',
    deckIncomplete: 'Deck unvollständig — Kämpfe erst mit {size} Karten möglich.',
    dishSlotHint: 'Max. {slots} Gericht pro Expedition',
    emptyCollection: 'Noch keine Karten geprägt.',
    ownedCopies: 'Besitz: {count}',
    inDeckCopies: 'Im Deck: {count}',
  },
  workshop: {
    openPrompt: '[E] {station} öffnen',
    close: 'Schließen [Esc]',
    craft: 'Herstellen',
    lockedHint: 'Benötigt Ausbaustufe {tier}',
    missingMaterial: 'fehlt',
    outputCard: 'Karte',
    outputDish: 'Gericht (Verbrauchskarte)',
    outputTool: 'Werkzeug',
    collectionCount: 'Sammlung: {count} Karten',
    crafted: '{name} hergestellt',
  },
  recipes: {
    tool_reinforced: {
      name: 'Verstärktes Werkzeug',
      description: 'Werkzeugstufe 2: Axtschlag 8 Schaden, Ernten +1 Ertrag.',
    },
  },
  cards: {
    axe_strike: { name: 'Axtschlag', description: '6 Schaden (skaliert mit Werkzeugstufe).' },
    wooden_shield: { name: 'Holzschild', description: '5 Block.' },
    stone_throw: { name: 'Steinwurf', description: '3 Schaden.' },
    catch_breath: { name: 'Verschnaufen', description: 'Ziehe 2 Karten.' },
    berry_snack: { name: 'Beerensnack', description: 'Heilt 5 HP. Verbrauchskarte.' },
    spark_strike: { name: 'Funkenschlag', description: '4 Schaden, ziehe 1 Karte.' },
    heavy_blow: { name: 'Schwerer Hieb', description: '10 Schaden.' },
    stone_wall: { name: 'Steinwall', description: '7 Block.' },
    throwing_axe: { name: 'Wurfbeil', description: '4 Schaden.' },
    armor_breaker: { name: 'Panzerbrecher', description: '6 Schaden, ignoriert Block.' },
    double_strike: { name: 'Doppelschlag', description: '2×4 Schaden.' },
    counter_stance: { name: 'Gegenhalten', description: '4 Block, Vergeltung 3.' },
    riposte: {
      name: 'Riposte',
      description: '6 Schaden. (+6 falls diese Runde geblockt — folgt.)',
    },
    pumpkin_stew: { name: 'Kürbiseintopf', description: 'Heilt 8 HP. Verbrauchskarte.' },
    chili_skewer: {
      name: 'Chili-Spieß',
      description: '+2 Stärke für den Kampf. Verbrauchskarte.',
    },
    fried_fish: {
      name: 'Gebratener Fisch',
      description: 'Heilt 6 HP, ziehe 1 Karte. Verbrauchskarte.',
    },
    splinter_bolt: { name: 'Splitterblitz', description: '8 Schaden, ziehe 1 Karte.' },
    crystal_shield: { name: 'Kristallschild', description: '5 Block, nächste Karte −1⚡.' },
    exhaustion: {
      name: 'Erschöpfung',
      description: 'Unspielbar. Verschwindet am Zugende.',
    },
    dazed: { name: 'Benommen', description: 'Unspielbar. Verschwindet am Zugende.' },
    rooted: {
      name: 'Verwurzelt',
      description: 'Unspielbar. Verstopft die Hand. Verschwindet am Zugende.',
    },
  },
  enemies: {
    shadow_rat: { name: 'Schattenratte' },
    shadow_rat_tutorial: { name: 'Schattenratte' },
    shadow_mouse: { name: 'Schattenmaus' },
    blighted_boar: { name: 'Befallenes Wildschwein' },
    thorn_creeper: { name: 'Dornenkriecher' },
    copper_beetle: { name: 'Kupferkäfer' },
    shadow_gull: { name: 'Schattenmöwe' },
    thorn_terror: { name: 'Dornenschreck' },
    root_warden: { name: 'Wurzelwächter' },
  },
  dungeonRun: {
    enterPrompt: '[E] {dungeon} betreten',
    roomProgress: 'Raum {current}/{total}',
    hpLabel: 'Lebenspunkte: {hp}/{maxHp}',
    noHealHint: 'Keine Heilung zwischen den Räumen.',
    startFight: 'Kampf beginnen',
    abandon: 'Aufgeben',
    abandonedLossToast: 'Aufgegeben — Beute verloren: {items}',
    abandonedNoLossToast: 'Aufgegeben — keine Beute verloren.',
    deckIncomplete: 'Deck unvollständig — der Kampf kann nicht beginnen.',
    npcRescued: '{npc} befreit!',
    orinRescuedBody:
      'Der Einsiedler-Magier Orin ist frei. Nach dem Dungeon kehrt er in die Heimatbucht zurück.',
    completedToast: '{dungeon} abgeschlossen! (+{xp} XP)',
    bossRoomHint: 'Der Wurzelwächter lauert hier.',
  },
  npcs: {
    orin: 'Orin',
    tilda: 'Tilda',
    maro: 'Maro',
    bruna: 'Bruna',
    piya: 'Piya',
    lumen: 'Lumen',
  },
  buildings: {
    b1: { name: 'Unterkunft', stages: ['Zelt', 'Hütte', 'Haus'] },
    b2: { name: 'Kochstelle', stages: ['Kochstelle', 'Küche St. 2', 'Küche St. 3'] },
    b3: { name: 'Schmiede', stages: ['Schmiede St. 1', 'Schmiede St. 2', 'Schmiede St. 3'] },
    b4: { name: 'Wohnhaus 1', stages: ['Wohnhaus 1'] },
    b5: { name: 'Steg', stages: ['Steg'] },
    b6: { name: 'Kristallschrein', stages: ['Kristallschrein'] },
    b7: { name: 'Wohnhaus 2', stages: ['Wohnhaus 2'] },
    b8: { name: 'Markt', stages: ['Markt'] },
    b9: { name: 'Bootshaus', stages: ['Bootshaus'] },
  },
  buildingEffects: {
    b1: 'Speichern; Haus: +1 Gericht-Slot auf Expedition (max. 2 gesamt).',
    b2: 'Schaltet Gerichte-Rezepte je Stufe frei.',
    b3: 'Schaltet Prägerezepte je Stufe frei; Werkzeug-Upgrades.',
    b4: 'Tilda zieht ein.',
    b5: 'Bruna zieht ein; Angeln.',
    b6: 'Verzaubern und Karten-Upgrade (später Resonanz).',
    b7: 'Orin zieht ein.',
    b8: 'Handel und Schwarzes Brett.',
    b9: 'Überfahrt zum Nebelwald (Insel 2).',
  },
  build: {
    slotPrompt: '[E] Bauplatz: {name}',
    panelTitle: 'Bauplatz',
    stageLabel: 'Ausbaustufe {stage}/{max}',
    notBuilt: 'Noch nicht gebaut',
    maxStage: 'Endausbau erreicht',
    nextStageHeading: 'Nächster Ausbau: {name}',
    costsHeading: 'Materialkosten',
    noCosts: 'Keine Materialkosten',
    requirementsHeading: 'Voraussetzungen',
    buildButton: 'Bauen',
    built: '{name} gebaut!',
    /** Text markers — fulfilled/missing never color-only (docs/11). */
    requirementMet: 'erfüllt',
    requirementMissing: 'fehlt',
    requirements: {
      onboarding: 'Ankunft auf der Insel',
      beat6: 'Story-Fortschritt (Beat 6)',
      island_cleansed: 'Insel gereinigt',
      piya_chain_complete: 'Piyas Bootskette abgeschlossen',
      npcRescued: '{npc} befreit',
      friendship: 'Freundschaft mit {npc}: Stufe {level}',
    },
  },
  dungeons: {
    verwachsene_hoehle: {
      name: 'Verwachsene Höhle',
      rooms: {
        cave_entrance: 'Höhleneingang',
        root_chamber: 'Wurzelkammer',
        thorn_passage: 'Dornengang',
        heart_of_the_cave: 'Herz der Höhle',
      },
    },
  },
  affixes: {
    armored: { name: 'Gepanzert' },
    thorned: { name: 'Dornig' },
    draining: { name: 'Zehrend' },
  },
  talismans: {
    heading: 'Talismane',
    slotsLabel: 'Talisman-Slots: {used}/{slots}',
    lockedHint: 'Talisman-Slot gesperrt — ab Stufe {level}.',
    equip: 'Anlegen',
    unequip: 'Ablegen',
    equipped: 'Angelegt',
    noneOwned: 'Noch keine Talismane gefunden.',
    obtainedToast: 'Talisman gefunden: {name}',
    thorn_ring: {
      name: 'Dornenring',
      description: 'Du startest jeden Kampf mit Vergeltung 1 (dauerhaft im Kampf).',
    },
  },
  progression: {
    levelLabel: 'Stufe {level}',
    xpLabel: 'XP: {current}/{next}',
    xpMax: 'XP: Maximum erreicht',
    levelUpToast: 'Stufe {level} erreicht!',
    xpGainToast: '+{amount} XP',
    explorationLabel: 'Erkundet: {percent} %',
    hpLabel: 'HP: {hp}/{max}',
    densityLabel: 'Schattendichte: {density}',
    cleansedLabel: 'Gereinigt',
  },
  exploration: {
    zoneNames: {
      strand: 'Strand',
      wiese: 'Wiese',
      waldrand: 'Waldrand',
    },
    areaDiscovered: 'Neues Gebiet: {zone} (+{xp} XP)',
    shrineDiscovered: 'Schrein entdeckt! (+{xp} XP)',
    secretDiscovered: 'Geheimnis entdeckt! (+{xp} XP)',
  },
  talents: {
    panelTitle: 'Talente',
    toggleHint: '[T] Talente',
    pointsAvailable: 'Talentpunkte: {points}',
    unlock: 'Freischalten',
    unlocked: 'Freigeschaltet',
    lockedRequiresPrevious: 'Gesperrt — benötigt vorherige Stufe',
    lockedNoPoints: 'Kein Talentpunkt verfügbar',
    tierLabel: 'Stufe {tier}',
    branches: {
      fighter: 'Kämpfer',
      crafter: 'Handwerker',
      wanderer: 'Wanderer',
    },
    blade_hone: {
      name: 'Klingenschliff',
      description: 'Der erste Angriff pro Kampf verursacht +2 Schaden.',
    },
    toughness: { name: 'Zähigkeit', description: '+5 maximale Lebenspunkte.' },
    bulwark: {
      name: 'Bollwerk',
      description: 'Start-Block +3 in Dungeon-Kämpfen.',
    },
    thrifty_hands: {
      name: 'Sparsame Hände',
      description:
        'Karten-Rezepte kosten 1 Basismaterial weniger (min. 1, Spezialmaterialien unberührt).',
    },
    good_cook: {
      name: 'Guter Koch',
      description: 'Gerichte wirken +25 % (aufgerundet).',
    },
    efficient_salvage: {
      name: 'Effizientes Zerlegen',
      description: 'Zerlegen erstattet 75 % statt 50 %.',
    },
    gatherers_luck: {
      name: 'Sammlerglück',
      description: '+1 Ertrag an Sammelstellen.',
    },
    loot_hunter: {
      name: 'Beutejäger',
      description: 'Kampfbeute +25 % (aufgerundet).',
    },
    map_savant: {
      name: 'Kartenkenner',
      description: 'Erkundungs-XP (Gebiet/Schrein) +50 %.',
    },
  },
} as const;

export type Strings = typeof strings;
