/**
 * Central string table (German first, see CLAUDE.md conventions).
 * All player-facing text must come from here — no literals in UI/world code.
 * Card/enemy IDs are English snake_case; display names live here.
 */
export const strings = {
  game: {
    title: 'Crystal Cove',
    helloIsland: 'Hallo Insel',
  },
  ui: {
    overlayReady: 'UI-Overlay aktiv',
    startTestCombat: 'Testkampf starten',
  },
  combat: {
    endTurn: 'Zug beenden',
    playerName: 'Du',
    retreatAttempt: 'Rückzugsversuch',
    drawPile: 'Nachziehstapel',
    discardPile: 'Ablagestapel',
    energy: 'Energie',
    block: 'Block',
    hp: 'Lebenspunkte',
    turn: 'Runde',
    locationChip: 'Heimatbucht · Dichte {density}',
    victoryTitle: 'Sieg!',
    lootHeading: 'Beute',
    defeatTitle: 'Erschöpft …',
    defeatBody: 'Du wachst sicher in deinem Bett auf.',
    retreatedTitle: 'Rückzug gelungen',
    retreatedBody: 'Du entkommst ohne Beute.',
    backToIsland: 'Zurück zur Insel',
    unplayable: 'Unspielbar',
    ignoresBlock: 'ignoriert Block',
    intents: {
      attack: 'Angriff',
      defend: 'Verteidigung',
      buff: 'Verstärkung',
      debuff: 'Schwächung',
      deck: 'Deck-Störung',
    },
    cardTypes: {
      attack: 'Angriff',
      skill: 'Fertigkeit',
      power: 'Kraft',
      dish: 'Gericht',
      status: 'Zustand',
    },
  },
  statuses: {
    strength: { name: 'Stärke', description: '+1 Schaden pro Punkt bei Angriffen.' },
    vulnerable: { name: 'Verwundbar', description: 'Erleidet 50 % mehr Angriffsschaden.' },
    weak: { name: 'Schwäche', description: 'Verursacht 25 % weniger Angriffsschaden.' },
    poison: { name: 'Gift', description: 'Verliert am Zugende HP in Höhe der Stapel, dann −1.' },
    retaliate: {
      name: 'Vergeltung',
      description: 'Angreifer erleiden Schaden in Höhe der Stapel.',
    },
  },
  world: {
    harvestNodes: {
      tree: 'Baum',
      rock: 'Fels',
      copper_vein: 'Kupferader',
      berry_bush: 'Beerenstrauch',
    },
    harvestPrompt: '[E] {node} ernten',
    harvestGain: '+{amount} {item}',
    lootToastHeading: 'Beute erhalten',
  },
  save: {
    recoveryNotice:
      'Spielstand wiederhergestellt: Der letzte Speicherstand war beschädigt, die Sicherungskopie wurde geladen.',
    recoveryDismiss: 'OK',
  },
  inventory: {
    title: 'Inventar',
    toggleHint: '[I] Inventar',
    empty: 'Noch nichts gesammelt.',
  },
  items: {
    wood: 'Holz',
    stone: 'Stein',
    shadow_fiber: 'Schattenfaser',
    shadow_dust: 'Schattenstaub',
    berry: 'Beere',
    tough_leather: 'Zähes Leder',
    meat: 'Fleisch',
    vine: 'Ranke',
    resin: 'Harz',
    copper_ore: 'Kupfererz',
    beetle_shell: 'Käferpanzer',
    feather: 'Feder',
    shiny_trinket: 'Glitzerkram',
    heart_thorn: 'Herzdorn',
    thorn_ring: 'Dornenring',
    pumpkin: 'Kürbis',
    chili: 'Chili',
    fish: 'Fisch',
    honey: 'Honig',
  },
  stations: {
    smithy: 'Schmiede',
    kitchen: 'Küche',
  },
  workshop: {
    openPrompt: '[E] {station} öffnen',
    close: 'Schließen [Esc]',
    craft: 'Herstellen',
    lockedHint: 'Benötigt Ausbaustufe {tier}',
    missingMaterial: 'fehlt',
    outputCard: 'Karte',
    outputDish: 'Gericht (Verbrauchskarte)',
    outputTool: 'Werkzeug',
    collectionCount: 'Sammlung: {count} Karten',
    crafted: '{name} hergestellt',
  },
  recipes: {
    tool_reinforced: {
      name: 'Verstärktes Werkzeug',
      description: 'Werkzeugstufe 2: Axtschlag 8 Schaden, Ernten +1 Ertrag.',
    },
  },
  cards: {
    axe_strike: { name: 'Axtschlag', description: '6 Schaden (skaliert mit Werkzeugstufe).' },
    wooden_shield: { name: 'Holzschild', description: '5 Block.' },
    stone_throw: { name: 'Steinwurf', description: '3 Schaden.' },
    catch_breath: { name: 'Verschnaufen', description: 'Ziehe 2 Karten.' },
    berry_snack: { name: 'Beerensnack', description: 'Heilt 5 HP. Verbrauchskarte.' },
    spark_strike: { name: 'Funkenschlag', description: '4 Schaden, ziehe 1 Karte.' },
    heavy_blow: { name: 'Schwerer Hieb', description: '10 Schaden.' },
    stone_wall: { name: 'Steinwall', description: '7 Block.' },
    throwing_axe: { name: 'Wurfbeil', description: '4 Schaden.' },
    armor_breaker: { name: 'Panzerbrecher', description: '6 Schaden, ignoriert Block.' },
    double_strike: { name: 'Doppelschlag', description: '2×4 Schaden.' },
    counter_stance: { name: 'Gegenhalten', description: '4 Block, Vergeltung 3.' },
    riposte: {
      name: 'Riposte',
      description: '6 Schaden. (+6 falls diese Runde geblockt — folgt.)',
    },
    pumpkin_stew: { name: 'Kürbiseintopf', description: 'Heilt 8 HP. Verbrauchskarte.' },
    chili_skewer: {
      name: 'Chili-Spieß',
      description: '+2 Stärke für den Kampf. Verbrauchskarte.',
    },
    fried_fish: {
      name: 'Gebratener Fisch',
      description: 'Heilt 6 HP, ziehe 1 Karte. Verbrauchskarte.',
    },
    splinter_bolt: { name: 'Splitterblitz', description: '8 Schaden, ziehe 1 Karte.' },
    crystal_shield: { name: 'Kristallschild', description: '5 Block, nächste Karte −1⚡.' },
    exhaustion: {
      name: 'Erschöpfung',
      description: 'Unspielbar. Verschwindet am Zugende.',
    },
    dazed: { name: 'Benommen', description: 'Unspielbar. Verschwindet am Zugende.' },
  },
  enemies: {
    shadow_rat: { name: 'Schattenratte' },
    shadow_rat_tutorial: { name: 'Schattenratte' },
    shadow_mouse: { name: 'Schattenmaus' },
    blighted_boar: { name: 'Befallenes Wildschwein' },
    thorn_creeper: { name: 'Dornenkriecher' },
    copper_beetle: { name: 'Kupferkäfer' },
    shadow_gull: { name: 'Schattenmöwe' },
    thorn_terror: { name: 'Dornenschreck' },
  },
  affixes: {
    armored: { name: 'Gepanzert' },
    thorned: { name: 'Dornig' },
    draining: { name: 'Zehrend' },
  },
} as const;

export type Strings = typeof strings;
