/**
 * Central string table (German first, see CLAUDE.md conventions).
 * All player-facing text must come from here — no literals in UI/world code.
 * Card/enemy IDs are English snake_case; display names live here.
 */
export const strings = {
  game: {
    title: 'Crystal Cove',
    helloIsland: 'Hallo Insel',
  },
  ui: {
    overlayReady: 'UI-Overlay aktiv',
    startTestCombat: 'Testkampf starten',
  },
  combat: {
    endTurn: 'Zug beenden',
    playerName: 'Du',
    retreatAttempt: 'Rückzugsversuch',
    drawPile: 'Nachziehstapel',
    discardPile: 'Ablagestapel',
    energy: 'Energie',
    block: 'Block',
    hp: 'Lebenspunkte',
    turn: 'Runde',
    locationChip: 'Heimatbucht · Dichte {density}',
    locationChipCleansed: 'Heimatbucht · Gereinigt',
    victoryTitle: 'Sieg!',
    lootHeading: 'Beute',
    defeatTitle: 'Erschöpft …',
    defeatBody: 'Du wachst sicher in deinem Zelt auf — vollständig erholt.',
    /** Defeat loot penalty (docs/03: 50 % der Run-Beute an die Schatten). */
    defeatLossHeading: 'Beute verloren',
    defeatNoLoss: 'Keine Beute verloren.',
    retreatedTitle: 'Rückzug gelungen',
    retreatedBody: 'Du entkommst ohne Beute.',
    backToIsland: 'Zurück zur Insel',
    unplayable: 'Unspielbar',
    ignoresBlock: 'ignoriert Block',
    /** Extra text on emphasized boss telegraphs (docs/07 Erdstampfer) —
     * information never via size/color alone (docs/11). */
    intentEmphasis: 'Achtung: schwerer Schlag!',
    dungeonLocationChip: '{dungeon} · Raum {room}/{total}',
    intents: {
      attack: 'Angriff',
      defend: 'Verteidigung',
      buff: 'Verstärkung',
      debuff: 'Schwächung',
      deck: 'Deck-Störung',
    },
    cardTypes: {
      attack: 'Angriff',
      skill: 'Fertigkeit',
      power: 'Kraft',
      dish: 'Gericht',
      status: 'Zustand',
    },
  },
  statuses: {
    strength: { name: 'Stärke', description: '+1 Schaden pro Punkt bei Angriffen.' },
    vulnerable: { name: 'Verwundbar', description: 'Erleidet 50 % mehr Angriffsschaden.' },
    weak: { name: 'Schwäche', description: 'Verursacht 25 % weniger Angriffsschaden.' },
    poison: { name: 'Gift', description: 'Verliert am Zugende HP in Höhe der Stapel, dann −1.' },
    retaliate: {
      name: 'Vergeltung',
      description: 'Angreifer erleiden Schaden in Höhe der Stapel.',
    },
  },
  world: {
    harvestNodes: {
      tree: 'Baum',
      rock: 'Fels',
      copper_vein: 'Kupferader',
      berry_bush: 'Beerenstrauch',
    },
    harvestPrompt: '[E] {node} ernten',
    farmPlot: 'Beet',
    plantPrompt: 'Pflanzen: [1] Beeren · [2] Kürbis · [3] Chili',
    growingPrompt: '{crop} wächst — noch {left}x schlafen',
    ripePrompt: '[E] {crop} ernten',
    sleepPrompt: '[E] Schlafen',
    sleepDone: 'Gut geschlafen! Die Insel erholt sich.',
    cropNames: {
      berry: 'Beeren',
      pumpkin: 'Kürbis',
      chili: 'Chili',
    },
    harvestGain: '+{amount} {item}',
    lootToastHeading: 'Beute erhalten',
    npcTalkPrompt: '[E] Mit {npc} sprechen',
    /** Quest-spawned collect points (docs/09; data/npcs questCollectNodes). */
    questCollectPrompt: '[E] {node} einsammeln',
    questNodes: {
      'quest-maro-toolbox': 'Werkzeugkiste',
      'quest-tilda-honey': 'Wilder Honig',
    },
  },
  dialog: {
    /** Blinking ▼ carries this label — never a glyph alone (docs/11). */
    continueLabel: 'Weiter',
    continueHint: 'Weiter: Klick oder Leertaste',
    choicesLabel: 'Antwort wählen',
    portraitLabel: 'Porträt: {npc}',
  },
  /** Dialog box texts (docs/13: max 2 Zeilen à ~60 Zeichen pro Box;
   * Lumen-Regel docs/06: max 1 Satz pro Box). Keys ← data/dialogs.ts. */
  dialogLines: {
    lumen_intro_1: 'Da bist du ja endlich — ich bin Lumen!',
    lumen_intro_2: 'Die Insel hat dich schon erwartet.',
    lumen_default_1: 'Die Insel atmet ruhiger, wenn du da bist.',

    // ── Maro (Schmied, docs/09) ─────────────────────────────────────────
    maro_arrival_1: 'Oh — Besuch! Ich bin Maro. Die alte Schmiede hier ist ein Traum.',
    maro_arrival_2: 'Wenn du Erz findest, bring es vorbei. Ich mache dir was Scharfes draus.',
    maro_default_1: 'Der Amboss singt heute wieder. Hörst du das?',
    maro_1_offer_1: 'Mein altes Werkzeug liegt noch im Wrack unten am Strand.',
    maro_1_offer_2: 'Holst du mir die Kiste? Dafür zeige ich dir den Schweren Hieb.',
    maro_1_reminder_1: 'Die Kiste liegt im Strandwrack, ganz im Westen.',
    maro_1_done_1: 'Meine alten Hämmer! Jetzt kann ich richtig loslegen.',
    maro_1_done_2:
      'Hier — das Rezept für den Schweren Hieb. Und die Schmiede baue ich dir gern aus.',
    maro_2_offer_1: 'Kupferkäferpanzer sind härter als alles, was ich gießen kann.',
    maro_2_offer_2: 'Bring mir drei davon, dann lernst du den Panzerbrecher.',
    maro_2_reminder_1: 'Drei Käferpanzer — die Kupferkäfer am Waldrand lassen sie manchmal fallen.',
    maro_2_done_1: 'Perfekt! Damit knackst du jeden Panzer — das Rezept gehört dir.',
    maro_3_offer_1: 'Ein Meisterstück braucht ein Herz. Ein Herzdorn, um genau zu sein.',
    maro_3_offer_2: 'Die tragen nur die ganz zähen Schattenwesen. Trau dich ran!',
    maro_3_reminder_1: 'Ein Herzdorn — such die Elite-Schatten, die haben so was.',
    maro_3_done_1: 'Da ist es. Mein Meisterstück: das Amboss-Herz.',
    maro_3_done_2: 'Trag es. Jeder Schild, den du hebst, hält ein Stück mehr aus.',

    // ── Tilda (Köchin, docs/09) ─────────────────────────────────────────
    tilda_arrival_1: 'Hallo! Ich bin Tilda. Das Wohnhaus ist wunderbar geworden.',
    tilda_arrival_2: 'Ab jetzt wird hier ordentlich gekocht — versprochen.',
    tilda_default_1: 'Irgendwas köchelt immer. Komm später auf einen Löffel vorbei.',
    tilda_1_offer_1: 'Für meinen Kürbiseintopf fehlen mir 5 Beeren und 2 Fleisch.',
    tilda_1_offer_2: 'Bringst du sie mir? Das Rezept teile ich natürlich mit dir.',
    tilda_1_reminder_1: 'Beeren wachsen auf der Wiese, Fleisch lassen die Wildschweine fallen.',
    tilda_1_done_1: 'Wunderbar! Der Eintopf-Duft gehört jetzt zur Bucht. Hier, dein Rezept.',
    tilda_2_offer_1: 'Frischer Fisch! Drei Stück, und ich zeige dir meinen Chili-Spieß.',
    tilda_2_offer_2: 'Bruna am Steg weiß, wie man sie aus dem Wasser holt.',
    tilda_2_reminder_1: 'Drei Fische — frag Bruna am Steg, sie hilft dir bestimmt.',
    tilda_2_done_1: 'Herrlich! Scharf, saftig — das Chili-Spieß-Rezept gehört dir.',
    tilda_3_offer_1: 'Ich träume von Honigglasur. Auf der Wiese summt es neuerdings …',
    tilda_3_offer_2: 'Magst du mir einen Wilden Honig besorgen? Nur einen!',
    tilda_3_reminder_1: 'Der Bienenstock steht auf der Wiese — pass auf die Finger auf.',
    tilda_3_done_1: 'Süßes Gold! Danke dir von Herzen.',
    tilda_3_done_2: 'Nimm diesen Talisman: ein warmer Bauch hat noch niemandem geschadet.',

    // ── Bruna (Fischerin, docs/09) ──────────────────────────────────────
    bruna_arrival_1: 'Ein Steg! Endlich wieder Planken unter den Füßen. Ich bin Bruna.',
    bruna_arrival_2: 'Ich bringe dir bei, wie man einen Treffer zurückgibt. Später.',
    bruna_default_1: 'Das Meer ist geduldig. Wir sollten es auch sein.',
    bruna_1_offer_1: 'Meine Netze sind hinüber. Vier feste Ranken, und ich knüpfe neue.',
    bruna_1_offer_2: 'Dafür zeige ich dir das Gegenhalten — Fischerinnen-Trick.',
    bruna_1_reminder_1: 'Vier Ranken — die Dornenkriecher lassen sie fallen.',
    bruna_1_done_1: 'Gute Arbeit. Hier: Gegenhalten. Wer dich trifft, spürt es jetzt selbst.',
    bruna_2_offer_1: 'Im tiefen Wasser wohnt ein Riesenwels. Ein alter Streit zwischen uns.',
    bruna_2_offer_2: 'Angle weiter — irgendwann beißt er an. Dann reden wir über die Riposte.',
    bruna_2_reminder_1: 'Der Riesenwels wartet. Wirf die Angel aus, immer wieder.',
    bruna_2_done_1: 'DER Wels! Ha! Abgemacht ist abgemacht: die Riposte gehört dir.',
    bruna_3_offer_1: 'Die Insel ist still geworden. Zeit für eine alte Geschichte.',
    bruna_3_offer_2: 'Setz dich zu mir, wenn du einen Moment hast.',
    bruna_3_reminder_1: 'Die Geschichte wartet auf dich, keine Sorge.',
    bruna_3_done_1: 'So war das damals mit dem Nebel. Jetzt weißt du es.',
    bruna_3_done_2: 'Nimm mein Seemannsgarn. Der erste Schild kostet dich nichts mehr.',

    // ── Orin (Einsiedler-Magier, docs/09) ───────────────────────────────
    orin_arrival_1: 'Du warst das in der Höhle, nicht wahr? Ich stehe in deiner Schuld.',
    orin_arrival_2: 'Ich bin Orin. Die Kristalle hier … sie flüstern wieder.',
    orin_default_1: 'Schattenstaub ist kein Abfall. Er ist Möglichkeit.',
    orin_1_offer_1: 'Errichte einen Kristallschrein — zehn Schattenstaub genügen.',
    orin_1_offer_2: 'Dann lehre ich dich den Splitterblitz.',
    orin_1_reminder_1:
      'Der Schrein wartet auf seinen Platz. Zehn Schattenstaub, mehr braucht es nicht.',
    orin_1_done_1: 'Der Schrein steht. Spürst du das Summen?',
    orin_1_done_2: 'Wie versprochen: der Splitterblitz. Präge ihn am Schrein.',
    orin_2_offer_1: 'Eine Resonanzprobe: Zieh mit drei verzauberten Karten in einen Kampf.',
    orin_2_offer_2: 'Dann zeige ich dir, wie man Karten dauerhaft verbessert.',
    orin_2_reminder_1: 'Drei verzauberte Karten im Deck, ein Kampf. Lass dir Zeit.',
    orin_2_done_1: 'Die Resonanz hält. Ab jetzt kannst du Karten am Schrein verstärken.',
    orin_3_offer_1: 'Die Insel ist rein. Der Schrein kann jetzt mehr — du auch.',
    orin_3_offer_2: 'Komm zu mir, wenn du bereit für den Kristallschild bist.',
    orin_3_reminder_1: 'Der Kristallschild wartet. Kein Grund zur Eile.',
    orin_3_done_1: 'Hier: der Kristallschild. Er schützt und schenkt Schwung.',
    orin_3_done_2: 'Du hast einem alten Einsiedler die Welt zurückgegeben. Danke.',

    // ── Piya (Händlerin, docs/09) ───────────────────────────────────────
    piya_arrival_1: 'Ahoi! Piya, fahrende Händlerin — na ja, gestrandete Händlerin.',
    piya_arrival_2: 'Mein Boot braucht Hilfe. Und du siehst nach Hilfe aus!',
    piya_default_1: 'Ein paar Waren habe ich immer dabei — mit Markt wird es erst richtig gut.',
    piya_1_offer_1: 'Der Rumpf ist ein Sieb. Ich brauche 10 Holz und 4 Zähes Leder.',
    piya_1_offer_2: 'Hilf mir, und ich nehme dich mit, wenn es wieder losgeht.',
    piya_1_reminder_1: '10 Holz, 4 Zähes Leder — der Rumpf wartet nicht ewig.',
    piya_1_done_1: 'Der Rumpf hält wieder dicht! Du bist Gold wert.',
    piya_2_offer_1: 'Jetzt die Fugen: 5 Harz, und das Boot schwimmt wie neu.',
    piya_2_offer_2: 'Die Dornenkriecher horten das Zeug, hab ich gehört.',
    piya_2_reminder_1: 'Fünf Harz für die Fugen — dann sind wir fast fertig.',
    piya_2_done_1: 'Abgedichtet! Bleibt nur noch eins: die Probefahrt.',
    piya_3_offer_1: 'Eine Runde um die Bucht — Probefahrt! Bist du dabei?',
    piya_3_offer_2: 'Wenn alles hält, steht uns der Nebelwald offen.',
    piya_3_reminder_1: 'Die Probefahrt wartet — das Wetter ist perfekt.',
    piya_3_done_1: 'Sie schwimmt! Keine Lecks, kein Knarzen.',
    piya_3_done_2: 'Bau das Bootshaus, dann planen wir die Überfahrt zum Nebelwald.',
  },
  /** Choice labels (docs/13: V1 nur Quest-Annahme und Piya-Handel). */
  dialogChoices: {
    quest_accept: 'Annehmen',
    quest_later: 'Später',
    trade_open: 'Zeig mir deine Waren',
  },
  save: {
    recoveryNotice:
      'Spielstand wiederhergestellt: Der letzte Speicherstand war beschädigt, die Sicherungskopie wurde geladen.',
    recoveryDismiss: 'OK',
  },
  inventory: {
    title: 'Inventar',
    toggleHint: '[I] Inventar',
    empty: 'Noch nichts gesammelt.',
  },
  /** Münzen (docs/10) — eigener Zähler, bewusst NICHT im Inventar-Panel. */
  coins: {
    name: 'Münzen',
    label: '{count} Münzen',
  },
  market: {
    title: 'Markt',
    openPrompt: '[E] Markt öffnen',
    sellHeading: 'Verkaufen',
    buyHeading: 'Piyas Sortiment',
    sellPriceLabel: '{price} Münzen/Stück',
    buyPriceLabel: '{price} Münzen',
    sellButton: 'Verkaufen',
    sellAllButton: 'Alle verkaufen',
    buyButton: 'Kaufen',
    soldToast: '{amount}× {item} verkauft (+{coins} Münzen)',
    boughtToast: '{item} gekauft (−{coins} Münzen)',
    notSellable: 'Unverkäuflich',
    notEnoughCoins: 'Nicht genug Münzen',
    nothingToSell: 'Nichts zu verkaufen.',
    /** V1: festes Sortiment; Rotation kommt mit der Weltkarte (docs/09). */
    stockHint: 'Piyas Vorrat wechselt, sobald wieder Boote fahren.',
  },
  board: {
    title: 'Schwarzes Brett',
    openPrompt: '[E] Schwarzes Brett lesen',
    activeHeading: 'Aktuelle Bitte',
    rewardLabel: 'Belohnung: {coins} Münzen',
    fulfillButton: 'Erfüllen',
    fulfilledToast: 'Bitte erfüllt (+{coins} Münzen)',
    /** Einmal pro Schlafphase — danach rotiert die Bitte (docs/10). */
    alreadyFulfilled: 'Für heute erledigt — nach dem Schlafen hängt eine neue Bitte aus.',
    missingItems: 'Dir fehlt noch etwas dafür.',
    /** Texte je Bitte (data/board) — Anzeige-Namen der 6 festen Bitten. */
    requests: {
      board_wood: 'Gesucht: 5 Holz für den Zaunbau.',
      board_berry: 'Gesucht: 3 Beeren für einen Kuchen.',
      board_stone: 'Gesucht: 3 Steine für den Wegebau.',
      board_fish: 'Gesucht: 2 Fische, möglichst frisch!',
      board_resin: 'Gesucht: 2 Harz zum Abdichten.',
      board_beetle_shell: 'Gesucht: 1 Käferpanzer — als Anschauungsstück.',
    },
  },
  fishing: {
    prompt: '[E] Angeln',
    caughtToast: '+{amount} Fisch geangelt!',
    giantCatfishToast: 'Der Riesenwels! Erzähl das Bruna!',
    /** 1 Fang pro Schlafphase (docs/09 V1) — danach beißt nichts mehr. */
    nothingBiting: 'Heute beißt nichts mehr — versuch es nach dem Schlafen wieder.',
  },
  questLog: {
    title: 'Quests',
    toggleHint: '[Q] Quests',
    activeHeading: 'Aktiv',
    completedHeading: 'Abgeschlossen',
    empty: 'Keine Quests — sprich mit den Bewohnern der Bucht.',
    giverLabel: 'Auftrag von {npc}',
    rewardLabel: 'Belohnung: {reward}',
    /** Turn-in-ready marker (docs/13 „?" ) — text, never color-only. */
    readyTag: 'abschlussbereit',
    questAcceptedToast: 'Quest angenommen: {name}',
    questCompletedToast: 'Quest abgeschlossen: {name} (+{xp} XP)',
  },
  /** Questlog texts per quest id (data/npcs) — name, goal, reward line. */
  quests: {
    maro_1: {
      name: 'Mein altes Werkzeug',
      goal: 'Birg Maros Werkzeugkiste aus dem Strandwrack (0/1).',
      reward: 'Rezept „Schwerer Hieb“',
    },
    maro_2: {
      name: 'Käferpanzer',
      goal: 'Bring Maro 3 Käferpanzer (Kupferkäfer-Drop).',
      reward: 'Rezept „Panzerbrecher“',
    },
    maro_3: {
      name: 'Das Meisterstück',
      goal: 'Bring Maro 1 Herzdorn (Elite-Drop).',
      reward: 'Talisman „Amboss-Herz“',
    },
    tilda_1: {
      name: 'Eintopf-Träume',
      goal: 'Bring Tilda 5 Beeren und 2 Fleisch.',
      reward: 'Rezept „Kürbiseintopf“',
    },
    tilda_2: {
      name: 'Fang des Tages',
      goal: 'Bring Tilda 3 Fische (Angeln am Steg — frag Bruna).',
      reward: 'Rezept „Chili-Spieß“',
    },
    tilda_3: {
      name: 'Süßes Gold',
      goal: 'Sammle 1 Wilden Honig auf der Wiese (0/1).',
      reward: 'Talisman „Warmer Bauch“',
    },
    bruna_1: {
      name: 'Alte Netze',
      goal: 'Bring Bruna 4 Ranken (Dornenkriecher-Drop).',
      reward: 'Rezept „Gegenhalten“',
    },
    bruna_2: {
      name: 'Der Riesenwels',
      goal: 'Fange den Riesenwels beim Angeln (0/1).',
      reward: 'Rezept „Riposte“',
    },
    bruna_3: {
      name: 'Brunas Geschichte',
      goal: 'Hör dir Brunas Geschichte an.',
      reward: 'Talisman „Seemannsgarn“',
    },
    orin_1: {
      name: 'Der Kristallschrein',
      goal: 'Errichte den Kristallschrein (10 Schattenstaub).',
      reward: 'Rezept „Splitterblitz“',
    },
    orin_2: {
      name: 'Resonanzprobe',
      goal: 'Bestehe 1 Kampf mit mind. 3 verzauberten Karten im Deck.',
      reward: 'Karten-Upgrade am Schrein',
    },
    orin_3: {
      name: 'Reines Licht',
      goal: 'Sprich mit Orin, sobald die Insel gereinigt ist.',
      reward: 'Rezept „Kristallschild“',
    },
    piya_1: {
      name: 'Leck im Rumpf',
      goal: 'Bring Piya 10 Holz und 4 Zähes Leder.',
      reward: 'Boot-Reparatur, Teil 1',
    },
    piya_2: {
      name: 'Dichte Fugen',
      goal: 'Bring Piya 5 Harz (Dornenkriecher-Drop).',
      reward: 'Boot-Reparatur, Teil 2',
    },
    piya_3: {
      name: 'Die Probefahrt',
      goal: 'Begleite Piya auf die Probefahrt.',
      reward: 'Bootshaus baubar (Überfahrt Nebelwald)',
    },
  },
  items: {
    wood: 'Holz',
    stone: 'Stein',
    shadow_fiber: 'Schattenfaser',
    shadow_dust: 'Schattenstaub',
    berry: 'Beere',
    tough_leather: 'Zähes Leder',
    meat: 'Fleisch',
    vine: 'Ranke',
    resin: 'Harz',
    copper_ore: 'Kupfererz',
    beetle_shell: 'Käferpanzer',
    feather: 'Feder',
    shiny_trinket: 'Glanzstück',
    heart_thorn: 'Herzdorn',
    thorn_ring: 'Dornenring',
    pumpkin: 'Kürbis',
    chili: 'Chili',
    fish: 'Fisch',
    honey: 'Honig',
    old_tools: 'Altes Werkzeug',
  },
  stations: {
    smithy: 'Schmiede',
    kitchen: 'Küche',
    deck_chest: 'Deck-Truhe',
  },
  deckChest: {
    collectionHeading: 'Sammlung',
    deckHeading: 'Deck ({count}/{size})',
    addToDeck: 'Ins Deck',
    removeFromDeck: 'Entfernen',
    disenchant: 'Zerlegen',
    disenchantConfirm: 'Wirklich zerlegen?',
    disenchantYes: 'Ja, zerlegen',
    disenchantNo: 'Abbrechen',
    refundPreview: 'Erstattung: {refund}',
    refundNothing: 'Erstattung: nichts',
    notDisenchantable: 'Starterkarte — nicht zerlegbar',
    deckIncomplete: 'Deck unvollständig — Kämpfe erst mit {size} Karten möglich.',
    dishSlotHint: 'Max. {slots} Gericht pro Expedition',
    emptyCollection: 'Noch keine Karten geprägt.',
    ownedCopies: 'Besitz: {count}',
    inDeckCopies: 'Im Deck: {count}',
  },
  workshop: {
    openPrompt: '[E] {station} öffnen',
    close: 'Schließen [Esc]',
    craft: 'Herstellen',
    lockedHint: 'Benötigt Ausbaustufe {tier}',
    missingMaterial: 'fehlt',
    outputCard: 'Karte',
    outputDish: 'Gericht (Verbrauchskarte)',
    outputTool: 'Werkzeug',
    collectionCount: 'Sammlung: {count} Karten',
    crafted: '{name} hergestellt',
  },
  recipes: {
    tool_reinforced: {
      name: 'Verstärktes Werkzeug',
      description: 'Werkzeugstufe 2: Axtschlag 8 Schaden, Ernten +1 Ertrag.',
    },
  },
  cards: {
    axe_strike: { name: 'Axtschlag', description: '6 Schaden (skaliert mit Werkzeugstufe).' },
    wooden_shield: { name: 'Holzschild', description: '5 Block.' },
    stone_throw: { name: 'Steinwurf', description: '3 Schaden.' },
    catch_breath: { name: 'Verschnaufen', description: 'Ziehe 2 Karten.' },
    berry_snack: { name: 'Beerensnack', description: 'Heilt 5 HP. Verbrauchskarte.' },
    spark_strike: { name: 'Funkenschlag', description: '4 Schaden, ziehe 1 Karte.' },
    heavy_blow: { name: 'Schwerer Hieb', description: '10 Schaden.' },
    stone_wall: { name: 'Steinwall', description: '7 Block.' },
    throwing_axe: { name: 'Wurfbeil', description: '4 Schaden.' },
    armor_breaker: { name: 'Panzerbrecher', description: '6 Schaden, ignoriert Block.' },
    double_strike: { name: 'Doppelschlag', description: '2×4 Schaden.' },
    counter_stance: { name: 'Gegenhalten', description: '4 Block, Vergeltung 3.' },
    riposte: {
      name: 'Riposte',
      description: '6 Schaden. (+6 falls diese Runde geblockt — folgt.)',
    },
    pumpkin_stew: { name: 'Kürbiseintopf', description: 'Heilt 8 HP. Verbrauchskarte.' },
    chili_skewer: {
      name: 'Chili-Spieß',
      description: '+2 Stärke für den Kampf. Verbrauchskarte.',
    },
    fried_fish: {
      name: 'Gebratener Fisch',
      description: 'Heilt 6 HP, ziehe 1 Karte. Verbrauchskarte.',
    },
    splinter_bolt: { name: 'Splitterblitz', description: '8 Schaden, ziehe 1 Karte.' },
    crystal_shield: { name: 'Kristallschild', description: '5 Block, nächste Karte −1⚡.' },
    exhaustion: {
      name: 'Erschöpfung',
      description: 'Unspielbar. Verschwindet am Zugende.',
    },
    dazed: { name: 'Benommen', description: 'Unspielbar. Verschwindet am Zugende.' },
    rooted: {
      name: 'Verwurzelt',
      description: 'Unspielbar. Verstopft die Hand. Verschwindet am Zugende.',
    },
  },
  enemies: {
    shadow_rat: { name: 'Schattenratte' },
    shadow_rat_tutorial: { name: 'Schattenratte' },
    shadow_mouse: { name: 'Schattenmaus' },
    blighted_boar: { name: 'Befallenes Wildschwein' },
    thorn_creeper: { name: 'Dornenkriecher' },
    copper_beetle: { name: 'Kupferkäfer' },
    shadow_gull: { name: 'Schattenmöwe' },
    thorn_terror: { name: 'Dornenschreck' },
    root_warden: { name: 'Wurzelwächter' },
  },
  dungeonRun: {
    enterPrompt: '[E] {dungeon} betreten',
    roomProgress: 'Raum {current}/{total}',
    hpLabel: 'Lebenspunkte: {hp}/{maxHp}',
    noHealHint: 'Keine Heilung zwischen den Räumen.',
    startFight: 'Kampf beginnen',
    abandon: 'Aufgeben',
    abandonedLossToast: 'Aufgegeben — Beute verloren: {items}',
    abandonedNoLossToast: 'Aufgegeben — keine Beute verloren.',
    deckIncomplete: 'Deck unvollständig — der Kampf kann nicht beginnen.',
    npcRescued: '{npc} befreit!',
    orinRescuedBody:
      'Der Einsiedler-Magier Orin ist frei. Nach dem Dungeon kehrt er in die Heimatbucht zurück.',
    completedToast: '{dungeon} abgeschlossen! (+{xp} XP)',
    bossRoomHint: 'Der Wurzelwächter lauert hier.',
  },
  npcs: {
    orin: 'Orin',
    tilda: 'Tilda',
    maro: 'Maro',
    bruna: 'Bruna',
    piya: 'Piya',
    lumen: 'Lumen',
  },
  buildings: {
    b1: { name: 'Unterkunft', stages: ['Zelt', 'Hütte', 'Haus'] },
    b2: { name: 'Kochstelle', stages: ['Kochstelle', 'Küche St. 2', 'Küche St. 3'] },
    b3: { name: 'Schmiede', stages: ['Schmiede St. 1', 'Schmiede St. 2', 'Schmiede St. 3'] },
    b4: { name: 'Wohnhaus 1', stages: ['Wohnhaus 1'] },
    b5: { name: 'Steg', stages: ['Steg'] },
    b6: { name: 'Kristallschrein', stages: ['Kristallschrein'] },
    b7: { name: 'Wohnhaus 2', stages: ['Wohnhaus 2'] },
    b8: { name: 'Markt', stages: ['Markt'] },
    b9: { name: 'Bootshaus', stages: ['Bootshaus'] },
  },
  buildingEffects: {
    b1: 'Speichern; Haus: +1 Gericht-Slot auf Expedition (max. 2 gesamt).',
    b2: 'Schaltet Gerichte-Rezepte je Stufe frei.',
    b3: 'Schaltet Prägerezepte je Stufe frei; Werkzeug-Upgrades.',
    b4: 'Tilda zieht ein.',
    b5: 'Bruna zieht ein; Angeln.',
    b6: 'Verzaubern und Karten-Upgrade (später Resonanz).',
    b7: 'Orin zieht ein.',
    b8: 'Handel und Schwarzes Brett.',
    b9: 'Überfahrt zum Nebelwald (Insel 2).',
  },
  build: {
    slotPrompt: '[E] Bauplatz: {name}',
    panelTitle: 'Bauplatz',
    stageLabel: 'Ausbaustufe {stage}/{max}',
    notBuilt: 'Noch nicht gebaut',
    maxStage: 'Endausbau erreicht',
    nextStageHeading: 'Nächster Ausbau: {name}',
    costsHeading: 'Materialkosten',
    noCosts: 'Keine Materialkosten',
    requirementsHeading: 'Voraussetzungen',
    buildButton: 'Bauen',
    built: '{name} gebaut!',
    /** Text markers — fulfilled/missing never color-only (docs/11). */
    requirementMet: 'erfüllt',
    requirementMissing: 'fehlt',
    requirements: {
      onboarding: 'Ankunft auf der Insel',
      beat6: 'Story-Fortschritt (Beat 6)',
      island_cleansed: 'Insel gereinigt',
      piya_chain_complete: 'Piyas Bootskette abgeschlossen',
      npcRescued: '{npc} befreit',
      friendship: 'Freundschaft mit {npc}: Stufe {level}',
    },
  },
  dungeons: {
    verwachsene_hoehle: {
      name: 'Verwachsene Höhle',
      rooms: {
        cave_entrance: 'Höhleneingang',
        root_chamber: 'Wurzelkammer',
        thorn_passage: 'Dornengang',
        heart_of_the_cave: 'Herz der Höhle',
      },
    },
  },
  affixes: {
    armored: { name: 'Gepanzert' },
    thorned: { name: 'Dornig' },
    draining: { name: 'Zehrend' },
  },
  talismans: {
    heading: 'Talismane',
    slotsLabel: 'Talisman-Slots: {used}/{slots}',
    lockedHint: 'Talisman-Slot gesperrt — ab Stufe {level}.',
    equip: 'Anlegen',
    unequip: 'Ablegen',
    equipped: 'Angelegt',
    noneOwned: 'Noch keine Talismane gefunden.',
    obtainedToast: 'Talisman gefunden: {name}',
    thorn_ring: {
      name: 'Dornenring',
      description: 'Du startest jeden Kampf mit Vergeltung 1 (dauerhaft im Kampf).',
    },
    warm_belly: {
      name: 'Warmer Bauch',
      description: 'Zu Kampfbeginn heilst du 3 HP.',
    },
    anvil_heart: {
      name: 'Amboss-Herz',
      description: 'Jede Verteidigungskarte gewährt +1 Block.',
    },
    sailors_yarn: {
      name: 'Seemannsgarn',
      description: 'Die erste Verteidigungskarte je Kampf kostet 0 Energie.',
    },
  },
  progression: {
    levelLabel: 'Stufe {level}',
    xpLabel: 'XP: {current}/{next}',
    xpMax: 'XP: Maximum erreicht',
    levelUpToast: 'Stufe {level} erreicht!',
    xpGainToast: '+{amount} XP',
    explorationLabel: 'Erkundet: {percent} %',
    hpLabel: 'HP: {hp}/{max}',
    densityLabel: 'Schattendichte: {density}',
    cleansedLabel: 'Gereinigt',
  },
  exploration: {
    zoneNames: {
      strand: 'Strand',
      wiese: 'Wiese',
      waldrand: 'Waldrand',
    },
    areaDiscovered: 'Neues Gebiet: {zone} (+{xp} XP)',
    shrineDiscovered: 'Schrein entdeckt! (+{xp} XP)',
    secretDiscovered: 'Geheimnis entdeckt! (+{xp} XP)',
  },
  talents: {
    panelTitle: 'Talente',
    toggleHint: '[T] Talente',
    pointsAvailable: 'Talentpunkte: {points}',
    unlock: 'Freischalten',
    unlocked: 'Freigeschaltet',
    lockedRequiresPrevious: 'Gesperrt — benötigt vorherige Stufe',
    lockedNoPoints: 'Kein Talentpunkt verfügbar',
    tierLabel: 'Stufe {tier}',
    branches: {
      fighter: 'Kämpfer',
      crafter: 'Handwerker',
      wanderer: 'Wanderer',
    },
    blade_hone: {
      name: 'Klingenschliff',
      description: 'Der erste Angriff pro Kampf verursacht +2 Schaden.',
    },
    toughness: { name: 'Zähigkeit', description: '+5 maximale Lebenspunkte.' },
    bulwark: {
      name: 'Bollwerk',
      description: 'Start-Block +3 in Dungeon-Kämpfen.',
    },
    thrifty_hands: {
      name: 'Sparsame Hände',
      description:
        'Karten-Rezepte kosten 1 Basismaterial weniger (min. 1, Spezialmaterialien unberührt).',
    },
    good_cook: {
      name: 'Guter Koch',
      description: 'Gerichte wirken +25 % (aufgerundet).',
    },
    efficient_salvage: {
      name: 'Effizientes Zerlegen',
      description: 'Zerlegen erstattet 75 % statt 50 %.',
    },
    gatherers_luck: {
      name: 'Sammlerglück',
      description: '+1 Ertrag an Sammelstellen.',
    },
    loot_hunter: {
      name: 'Beutejäger',
      description: 'Kampfbeute +25 % (aufgerundet).',
    },
    map_savant: {
      name: 'Kartenkenner',
      description: 'Erkundungs-XP (Gebiet/Schrein) +50 %.',
    },
  },
} as const;

export type Strings = typeof strings;
